pipeline {
    agent any
    environment {
        ENVIRONMENT = "staging"
    }
    stages {

        stage('Get Code'){
            steps{
                checkout scm
            }
        }
        
        stage('SetUp'){
            steps{
                echo 'Setup Virtualenv for testing'
                sh "bash pipelines/PIPELINE-FULL-STAGING/setup.sh"
            }
        }
        stage('Test'){
            steps{
                echo 'Static program analysis:'
                sh "bash pipelines/PIPELINE-FULL-STAGING/static_test.sh"
                archiveArtifacts artifacts: 'reports/*', fingerprint: true
                echo 'Unit testing:'
                sh "bash pipelines/PIPELINE-FULL-STAGING/unit_test.sh"
            }
            post {
                always {
                        archiveArtifacts artifacts: 'coverage.xml, reports/*', fingerprint: true, allowEmptyArchive: true
                    }
                }            
        }
       stage('Build') {
            steps{
                echo 'Package sam application:'
                sh "bash pipelines/common-steps/build.sh"
            }
        }
        stage('Deploy'){
            steps{
                echo 'Initiating Deployment'
                sh "bash pipelines/common-steps/deploy.sh"
            }
        }
        stage('Integration Test after deploy'){
            steps{
                script {
                    def BASE_URL = sh( script: "aws cloudformation describe-stacks --stack-name todo-list-aws-staging --query 'Stacks[0].Outputs[?OutputKey==`BaseUrlApi`].OutputValue' --region us-east-1 --output text",
                        returnStdout: true)
                    echo "$BASE_URL"
                    echo 'Initiating Integration Tests'
                    sh "bash pipelines/common-steps/integration.sh $BASE_URL"
                }
                   
            }
        }
        stage('Promote (merge develop -> master)'){
            steps{
                sh '''
                    git config user.email "mogollortega@gmail.com "
                    git config user.name "TheMogoalex"
                    git fetch origin
                    git checkout master
                    git pull origin master
                    git merge --no-ff origin/develop -m "Promote develop -> master"
                    '''
                sshagent(['github']) {
                    sh '''
                    mkdir -p ~/.ssh
                    ssh-keyscan -H github.com >> ~/.ssh/known_hosts
                    '''
                    sh 'git push origin master'
                }
            }
        }
    }
    post { 
        always { 
            echo 'Clean env: delete dir'
            cleanWs()
        }
    }
}